In [14]:
class Algorithms(object):
    # INSERTION SORT (n^2)
    def INSERTION_SORT(self, lst):
        for j in range(1, len(lst)):
            key = lst[j]
            i = j - 1
            while i >= 0 and lst[i] > key:
                lst[i+1] = lst[i]
                i -= 1
            lst[i + 1] = key
    
    # MERGE SORT (nlgn)
    def MERGE(self, lst, p, q, r):
        n1 = q - p + 1
        n2 = r - q
        L = [float('inf')] * (n1 + 1)
        R = [float('inf')] * (n2 + 1)

        for i in range(n1):
            L[i] = lst[p + i]
        for j in range(n2):
            R[j] = lst[q + j + 1]

        i, j = 0, 0

        for k in range(p, r+1):
            if L[i] <= R[j]:
                lst[k] = L[i]
                i += 1
            else:
                lst[k] = R[j]
                j += 1
                
    def MERGE_SORT(self, lst, p, r):
        if p < r:
            q = (p + r) // 2
            self.MERGE_SORT(lst, p, q)
            self.MERGE_SORT(lst, q + 1, r)
            self.MERGE(lst, p, q, r)
    
    # FIND MAXIMUM SUBARRAY (nlgn)
    def FIND_MAX_CROSSING_SUBARRAY(self, lst, low, mid, high):
        left_sum = float('-inf')
        sum = 0
        for i in range(mid, low-1, -1):
            sum += lst[i]
            if sum > left_sum:
                left_sum = sum
                max_left = i

        right_sum = float('-inf')
        sum = 0
        for j in range(mid+1, high+1):
            sum += lst[j]
            if sum > right_sum:
                right_sum = sum
                max_right = j
        return (max_left, max_right, left_sum + right_sum)

    def FIND_MAXIMUM_SUBARRAY(self, lst, low, high):
        if high == low:
            return (low, high, lst[low])
        else:
            mid = (low + high) // 2
            (left_low, left_high, left_sum) = self.FIND_MAXIMUM_SUBARRAY(lst, low, mid)
            (right_low, right_high, right_sum) = self.FIND_MAXIMUM_SUBARRAY(lst, mid+1, high)
            (cross_low, cross_high, cross_sum) = self.FIND_MAX_CROSSING_SUBARRAY(lst, low, mid, high)
            if left_sum >= right_sum and left_sum >= cross_sum:
                return (left_low, left_high, left_sum)
            elif right_sum >= left_sum and right_sum >= cross_sum:
                return (right_low, right_high, right_sum)
            else:
                return (cross_low, cross_high, cross_sum)
    
    def SQUARE_MATRIX_MULTIPLY(self, A, B):
        n = len(A)
        C = [[0] * n for _ in range(n)]
        for i in range(n):
            for j in range(n):
                c_ij = 0
                for k in range(n):
                    c_ij += A[i][k] * B[k][j]
                    C[i][j] = c_ij
        return C
    
    def SQUARE_MATRIX_MULPIPLY_RECURSIVE(self, A, B):
        n = len(A)
        C = [[0] * n for _ in range(n)]
        if n == 1:
            C[0][0] = A[0][0] * B[0][0]
        # TODO
        else:
            i, j = 0, 0
            C[i][j] = self.SQUARE_MATRIX_MULPIPLY_RECURSIVE(A[i][j], B[i][j]) + self.SQUARE_MATRIX_MULPIPLY_RECURSIVE(A[i][j+1], B[i+1][j])
            C[i][j+1] = self.SQUARE_MATRIX_MULPIPLY_RECURSIVE(A[i][j], B[i][j+1]) + self.SQUARE_MATRIX_MULPIPLY_RECURSIVE(A[i][j+1], B[i+1][j+1])
            C[i+1][j] = self.SQUARE_MATRIX_MULPIPLY_RECURSIVE(A[i+1][j], B[i][j]) + self.SQUARE_MATRIX_MULPIPLY_RECURSIVE(A[i+1][j+1], B[i+1][j])
            C[i+1][j+1] = self.SQUARE_MATRIX_MULPIPLY_RECURSIVE(A[i+1][j], B[i][j+1]) + self.SQUARE_MATRIX_MULPIPLY_RECURSIVE(A[i+1][j+1], B[i+1][j+1])
        return C



In [36]:
A = Algorithms()
lst = [4, 8, 10, 2, 0, 9]

In [11]:
# INSERTION SORT
A.INSERTION_SORT(lst)
lst

[0, 2, 4, 8, 9, 10]

In [37]:
# MERGE SORT
A.MERGE_SORT(lst, 0, len(lst) - 1)
lst

[0, 2, 4, 8, 9, 10]

In [44]:
A = Algorithms()
lst = [-4, 8, 10, -2, 0, 9, -12, -4, 100, -40, 3, 24, -1]

In [46]:
(low, high, sum) = A.FIND_MAXIMUM_SUBARRAY(lst, 0, len(lst)-1)
(low, high, sum)

(1, 8, 109)

In [15]:
A = Algorithms()
MA = [[1, 2, 3], [4, 5, 6], [7, 8 ,9]]
MB = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
MC = A.SQUARE_MATRIX_MULTIPLY(MA, MB)
MC

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]

In [11]:
import numpy as np

# Define matrices X and Y (same as above)
X = np.array(MA)
Y = np.array(MB)

# Perform matrix multiplication
result = np.matmul(X, Y)

# Print the result
print(result)


[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
